# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97b717e8c8927f0c5114d741bd740bec4ed6f6a05ae512ca6c8ef22108f3fe32422955f4c5c3b2e9e1951d77318caa0e8fcf2f4143c6b259ebfa080befc821b

test:
  secret_key_base: 7dedf723c5401218f0a9851c68bf42176599adc67dd24f2e1d98841288fb6b03b7159a0ae86b35e41896b597414d945bb2825e91cbb711686c228d528fa6ab4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
